# Generated by Django 5.0.14 on 2026-05-07 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("locations", "0001_initial"),
        ("pricing", "0001_initial"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("qr_code", models.CharField(blank=True, max_length=255)),
                (
                    "express_code",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("battery", "Battery"),
                            ("fragile", "Fragile"),
                            ("document", "Document"),
                            ("electronics", "Electronics"),
                            ("clothing", "Clothing"),
                            ("shoes", "Shoes"),
                            ("furniture", "Furniture"),
                            ("custom", "Custom"),
                        ],
                        default="standard",
                        max_length=50,
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("air", "Air"),
                            ("rail", "Rail"),
                            ("sea", "Sea"),
                            ("mixed", "Mixed"),
                            ("other", "Other"),
                        ],
                        default="auto",
                        max_length=50,
                    ),
                ),
                ("place_count", models.IntegerField(default=1)),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "length_cm",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "width_cm",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "height_cm",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "volume_m3",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "volume_source",
                    models.CharField(
                        choices=[("calculated", "Calculated"), ("manual", "Manual")],
                        default="calculated",
                        max_length=20,
                    ),
                ),
                (
                    "declared_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "declared_value_currency",
                    models.CharField(default="USD", max_length=10),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("weight", "Weight"),
                            ("volume", "Volume"),
                            ("fixed", "Fixed"),
                            ("manual", "Manual"),
                        ],
                        default="weight",
                        max_length=50,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=50,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("at_china_warehouse", "At China Warehouse"),
                            ("measured", "Measured"),
                            ("photographed", "Photographed"),
                            ("labeled", "Labeled"),
                            ("packed", "Packed"),
                            ("grouped", "Grouped"),
                            ("sent_to_uzbekistan", "Sent to Uzbekistan"),
                            ("arrived_uzbekistan", "Arrived Uzbekistan"),
                            ("sent_to_turkmenistan", "Sent to Turkmenistan"),
                            ("arrived_turkmenistan", "Arrived Turkmenistan"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                (
                    "warehouse_stage",
                    models.CharField(
                        choices=[
                            ("intake", "Intake"),
                            ("measured", "Measured"),
                            ("photographed", "Photographed"),
                            ("labeled", "Labeled"),
                            ("packed", "Packed"),
                            ("grouped", "Grouped"),
                            ("dispatched", "Dispatched"),
                        ],
                        default="intake",
                        max_length=50,
                    ),
                ),
                (
                    "calculated_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "external_expenses_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("description", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                ("is_fragile", models.BooleanField(default=False)),
                ("has_battery", models.BooleanField(default=False)),
                ("is_repacked", models.BooleanField(default=False)),
                ("is_dangerous", models.BooleanField(default=False)),
                ("requires_manual_review", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="locations.destination",
                    ),
                ),
                (
                    "price_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="pricing.pricerule",
                    ),
                ),
                (
                    "shipment_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="shipments.shipmentgroup",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="locations.warehouse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("packing_list", "Packing List"),
                            ("customs_doc", "Customs Doc"),
                            ("label", "Label"),
                            ("identity_doc", "Identity Doc"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/")),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="clients.client",
                    ),
                ),
                (
                    "shipment_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="shipments.shipmentgroup",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="items.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("wood_packing", "Wood Packing"),
                            ("repack", "Repack"),
                            ("fragile_handling", "Fragile Handling"),
                            ("battery_handling", "Battery Handling"),
                            ("storage_fee", "Storage Fee"),
                            ("loading_fee", "Loading Fee"),
                            ("relabeling", "Relabeling"),
                            ("customs_support", "Customs Support"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="items.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="items/photos/")),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="items.item",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=50)),
                ("new_status", models.CharField(max_length=50)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="items.item",
                    ),
                ),
            ],
        ),
    ]
