# Generated by Django 5.0.14 on 2026-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Груз", "verbose_name_plural": "Грузы"},
        ),
        migrations.AlterModelOptions(
            name="itemexpense",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Доп. расход",
                "verbose_name_plural": "Доп. расходы",
            },
        ),
        migrations.AlterModelOptions(
            name="itemphoto",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Фото груза",
                "verbose_name_plural": "Фото грузов",
            },
        ),
        migrations.AlterModelOptions(
            name="itemstatushistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "История статуса груза",
                "verbose_name_plural": "Истории статусов грузов",
            },
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Инвойс"),
                    ("waybill", "Накладная"),
                    ("customs_doc", "Таможенный документ"),
                    ("other", "Другое"),
                    ("identity_doc", "Identity Doc"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("at_china_warehouse", "На складе в Китае"),
                    ("measured", "Измерен"),
                    ("photographed", "Сфотографирован"),
                    ("labeled", "Маркирован"),
                    ("packed", "Упакован"),
                    ("grouped", "Добавлен в партию"),
                    ("sent_to_uzbekistan", "Отправлен в Узбекистан"),
                    ("arrived_uzbekistan", "Прибыл в Узбекистан"),
                    ("sent_to_turkmenistan", "Отправлен в Туркменистан"),
                    ("arrived_turkmenistan", "Прибыл в Туркменистан"),
                    ("out_for_delivery", "На доставке"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                ],
                default="created",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("standard", "Стандартный"),
                    ("electronics", "Электроника"),
                    ("clothing", "Одежда"),
                    ("fragile", "Хрупкий"),
                    ("dangerous", "Опасный"),
                ],
                default="standard",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Не оплачено"),
                    ("partially_paid", "Частично оплачено"),
                    ("paid", "Оплачено"),
                    ("refunded", "Возврат"),
                ],
                default="unpaid",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("weight", "По весу"),
                    ("volume", "По объему"),
                    ("fixed", "Фиксированный"),
                    ("mixed", "Смешанный"),
                ],
                default="weight",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="transport_type",
            field=models.CharField(
                choices=[
                    ("auto", "Авто"),
                    ("avia", "Авиа"),
                    ("rail", "Ж/Д"),
                    ("sea", "Море"),
                ],
                default="auto",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="volume_source",
            field=models.CharField(
                choices=[
                    ("calculated", "Рассчитан из габаритов"),
                    ("manual", "Введён вручную"),
                ],
                default="calculated",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="warehouse_stage",
            field=models.CharField(
                choices=[
                    ("intake", "Приёмка"),
                    ("measured", "Измерение"),
                    ("photographed", "Фото"),
                    ("labeled", "Маркировка"),
                    ("packed", "Упаковка"),
                    ("grouped", "В партии"),
                    ("dispatched", "Отправлен"),
                ],
                default="intake",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="itemexpense",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("packaging", "Упаковка"),
                    ("storage", "Хранение"),
                    ("insurance", "Страховка"),
                    ("custom", "Другое"),
                ],
                max_length=50,
            ),
        ),
    ]
