# Generated by Django 5.0.14 on 2026-05-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_attachment_options_alter_item_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("at_china_warehouse", "На складе в Китае"),
                    ("measured", "Измерен"),
                    ("photographed", "Сфотографирован"),
                    ("labeled", "Маркирован"),
                    ("packed", "Упакован"),
                    ("grouped", "Добавлен в партию"),
                    ("sent_to_urumqi", "Отправлен в Урумчи"),
                    ("arrived_urumqi", "Прибыл в Урумчи"),
                    ("sent_to_turkmenistan", "Отправлен в Туркменистан"),
                    ("arrived_turkmenistan", "Прибыл в Туркменистан"),
                    ("out_for_delivery", "На доставке"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                ],
                default="created",
                max_length=50,
            ),
        ),
    ]
