# Generated by Django 5.0.14 on 2026-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_item_delivery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="main_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="items/main_photos/",
                verbose_name="Основное фото (коллаж)",
            ),
        ),
    ]
