# Generated by Django 5.0.14 on 2026-05-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("weight", "Weight"),
                            ("volume", "Volume"),
                            ("fixed", "Fixed"),
                            ("mixed", "Mixed"),
                            ("manual", "Manual"),
                        ],
                        default="weight",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("CNY", "CNY"),
                            ("TMT", "TMT"),
                            ("UZS", "UZS"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "price_per_m3",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "fixed_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "min_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("extra_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_rules",
                        to="locations.destination",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_rules",
                        to="locations.warehouse",
                    ),
                ),
            ],
        ),
    ]
