# Generated by Django 5.0.14 on 2026-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricerule",
            options={
                "ordering": ["-priority"],
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
            },
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("weight", "За КГ"),
                    ("volume", "За Куб"),
                    ("fixed", "Фиксированная"),
                    ("mixed", "Смешанная (Макс)"),
                ],
                default="weight",
                max_length=20,
            ),
        ),
    ]
