# Generated by Django 5.0.14 on 2026-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffuser",
            options={"verbose_name": "Сотрудник", "verbose_name_plural": "Сотрудники"},
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Суперадмин"),
                    ("admin", "Администратор"),
                    ("manager", "Менеджер"),
                    ("operator", "Оператор"),
                    ("warehouse", "Складской сотрудник"),
                ],
                default="operator",
                max_length=20,
            ),
        ),
    ]
