# Generated by Django 5.1.15 on 2026-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_staffuser_options_alter_staffuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Суперадмин"),
                    ("admin", "Администратор"),
                    ("manager", "Менеджер"),
                    ("operator", "Оператор"),
                    ("warehouse", "Складской сотрудник"),
                    ("client", "Клиент"),
                ],
                default="operator",
                max_length=20,
            ),
        ),
    ]
