# Generated by Django 5.0.14 on 2026-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
            },
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("card", "Карта"),
                    ("bank_transfer", "Банковский перевод"),
                    ("wechat", "WeChat"),
                    ("alipay", "Alipay"),
                ],
                default="cash",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("completed", "Завершен"),
                    ("failed", "Ошибка"),
                    ("cancelled", "Отменён"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("payment", "Платёж"), ("refund", "Возврат")],
                default="payment",
                max_length=50,
            ),
        ),
    ]
