# Generated by Django 5.0.14 on 2026-05-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="destination",
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"verbose_name": "Склад", "verbose_name_plural": "Склады"},
        ),
    ]
