# Generated by Django 5.0.14 on 2026-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipmentgroup",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Партия",
                "verbose_name_plural": "Партии",
            },
        ),
        migrations.AlterField(
            model_name="shipmentgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("forming", "Формируется"),
                    ("ready_to_dispatch", "Готов к отправке"),
                    ("in_transit_to_uzbekistan", "В пути в Узбекистан"),
                    ("arrived_uzbekistan", "Прибыл в Узбекистан"),
                    ("in_transit_to_turkmenistan", "В пути в Туркменистан"),
                    ("arrived_turkmenistan", "Прибыл в Туркменистан"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменён"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
