# Generated by Django 5.0.14 on 2026-05-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_alter_shipmentgroup_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipmentgroup",
            old_name="arrived_uzbekistan_date",
            new_name="arrived_urumqi_date",
        ),
        migrations.RenameField(
            model_name="shipmentgroup",
            old_name="china_to_uzbekistan_cost",
            new_name="china_to_urumqi_cost",
        ),
        migrations.RenameField(
            model_name="shipmentgroup",
            old_name="sent_to_uzbekistan_date",
            new_name="sent_to_urumqi_date",
        ),
        migrations.AlterField(
            model_name="shipmentgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("forming", "Формируется"),
                    ("ready_to_dispatch", "Готов к отправке"),
                    ("in_transit_to_urumqi", "В пути в Урумчи"),
                    ("arrived_urumqi", "Прибыл в Урумчи"),
                    ("in_transit_to_turkmenistan", "В пути в Туркменистан"),
                    ("arrived_turkmenistan", "Прибыл в Туркменистан"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменён"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
