# Generated by Django 5.0.14 on 2026-05-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Журнал действий",
                "verbose_name_plural": "Журнал действий",
            },
        ),
    ]
