# Generated by Django 5.0.14 on 2026-05-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, unique=True
            ),
        ),
    ]
