# Generated by Django 5.0.14 on 2026-05-28 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_user"),
        ("items", "0006_remove_box"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Валюта"
                    ),
                ),
                (
                    "requires_comment",
                    models.BooleanField(
                        default=False, verbose_name="Требует комментарий"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Доп. услуга",
                "verbose_name_plural": "Доп. услуги",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="delivery_city",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Город доставки"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=10, verbose_name="Язык"),
        ),
        migrations.AddField(
            model_name="client",
            name="wechat",
            field=models.CharField(blank=True, max_length=50, verbose_name="WeChat"),
        ),
        migrations.AddField(
            model_name="client",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=30, verbose_name="WhatsApp"),
        ),
        migrations.CreateModel(
            name="CargoService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнено"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("comment", models.TextField(blank=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_services",
                        to="items.item",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_services",
                        to="clients.client",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="clients.additionalservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос услуги",
                "verbose_name_plural": "Запросы услуг",
                "ordering": ["-created_at"],
            },
        ),
    ]
