# Generated by Django 5.0.14 on 2026-05-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0003_alter_client_client_code"),
        ("items", "0004_item_main_photo"),
        (
            "shipments",
            "0003_rename_arrived_uzbekistan_date_shipmentgroup_arrived_urumqi_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("push", "Push-уведомление"),
                            ("internal", "Внутреннее"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="Канал",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("item_received", "Груз принят"),
                            ("item_sent", "Груз отправлен"),
                            ("item_arrived", "Груз прибыл"),
                            ("ready_for_pickup", "Готов к выдаче"),
                            ("payment_due", "Ожидается оплата"),
                            ("custom", "Произвольное"),
                        ],
                        max_length=30,
                        verbose_name="Тип",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Данные"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено в"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="items.item",
                        verbose_name="Груз",
                    ),
                ),
                (
                    "shipment_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="shipments.shipmentgroup",
                        verbose_name="Партия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
    ]
