# Generated by Django 5.0.14 on 2026-05-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Прочитано в"
            ),
        ),
    ]
