# Generated by Django 5.0.14 on 2026-05-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_seed_services"),
        ("notifications", "0002_notification_read_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=512, unique=True, verbose_name="Токен"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        default="android",
                        max_length=10,
                        verbose_name="Платформа",
                    ),
                ),
                (
                    "push_service",
                    models.CharField(
                        choices=[
                            ("console", "Console (dev)"),
                            ("fcm", "Firebase (Android Global)"),
                            ("jpush", "JPush 极光 (China)"),
                            ("getui", "GeTui 个推 (China)"),
                            ("umeng", "Umeng 友盟 (China)"),
                            ("huawei", "Huawei Push"),
                            ("apns", "Apple APNs (iOS)"),
                        ],
                        default="console",
                        max_length=20,
                        verbose_name="Push-сервис",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Устройство",
                "verbose_name_plural": "Устройства (push)",
                "ordering": ["-created_at"],
            },
        ),
    ]
